<?php

function mw_modal_links_field_collection_item_view_alter(&$build) {
      // Modal page sidebar links and the related anchor tags that wrap around section titles.
  if ($build['#bundle'] = 'modal_page') {
    if ($build['#view_mode'] == 'full') {

      $anchortext = strtolower(str_replace(" ","-", $build['field_section_title'][0]['#markup']));
      // Provide markup for modal page card links
      if ($build['field_section_title'][0]['#markup']){
      $build['field_section_title'][0]['#cardlinktext'] = $anchortext . '">' .$build['field_section_title'][0]['#markup']. '</a></li>';
        }
      // Provide markup for modal page sidebar links
      if ($build['field_section_title'][0]['#markup']){
      $build['field_section_title'][0]['#linktext'] = '<li><a href="#'.$anchortext . '">' .$build['field_section_title'][0]['#markup']. '</a></li>';
        }
      // Provide markup for modal page section titles
      if ($build['field_section_title'][0]['#markup']){
        $build['field_section_title'][0]['#markup'] = '<a name="'.$anchortext . '"></a><h2>' .$build['field_section_title'][0]['#markup']. '</h2>';
      }else{
        $build['field_section_title'][0]['#markup'] = NULL;
      }

      //dpm($build);
    }
  }
}
